### ISSUE TITLE
Setup and Write tests

### ISSUE THREAD

**Issue by sergiopvilar** [AnansiPodcast/anansi#30]
We need to write some unit and fuctional tests to assure that the changes won't break the app state.

**Acceptance criteria:**
- The app should have a basic test suit for both unit and functional tests
- Functional tests should be implemented using [Spectron](https://github.com/electron/spectron)
- Unit tests should be implemented using [Mocha](https://mochajs.org/)
- All test codebase should be written in ES2015

**Modules to be tested with unit tests:**
- [x] PodcastController (5a33ff0f1b164c00c7848a360ef1a0f12db2a99e)
- [x] EpisodeController (26746f55bcdbc76342b20ec49d90fdbd0ca2810f)
- [x] Interval for fetching new episodes (8a30c4a06f3ed6e56d77e53e0ce5a55f031bb3b3)
